[package]
authors = ["dmitry"]
edition = "2018"
name = "parsley"
version = "0.1.0"

[workspace]
members = [".", "parsley_wal", "core", "rangetree", "pmem_storage"]

[dependencies]
futures = "*"
futures-lite = "*" # TODO REMOVE
enum_dispatch = "*"
core = { path = "core" }
rangetree = { path = "rangetree" }
log = "*"
env_logger = "*"
glommio = { path = "../glommio/glommio" }

[profile.release]
debug = true