[package]
name = "parsley_durable_log"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "*"
futures-lite = "*"
glommio = "0.7"
crc32fast = "1.2.1"
thiserror = "1.0.25"
histogram = "0.6.9"


[[bench]]
name = "bench_simple_write"
harness = false
