[package]
name = "parsley_wal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "*"
futures-lite = "*"
glommio = { path = "../../glommio/glommio" }
crc32fast = "1.2.1"
thiserror = "1.0.25"
